@startuml
start
:Исходные материалы
 - Печатная плата (rev 1.2)
 - SMD-компоненты
 - 3D-печатный корпус
 - Средняя пластина
 - Светодиодная лента для средней пластины (WS2812B)
 - Аккумулятор
 - Верхняя часть диспенсера таблеток;
group "Сборка печатной платы"
    :Очистить плату изопропиловым спиртом;
    :Нанести паяльную пасту с помощью металлического трафарета;
    :Установить SMD-компоненты;
    :Пропаять плату в печи оплавления;
    :Припаять выводные компоненты вручную;
    :Припаять аккумулятор к плате;
end group
group "Сборка средней пластины"
    :Отрезать светодиодную ленту по длине (2X2 или 4X7);
    :Припаять провода к светодиодной ленте;
    :Припаять транзистор питания к проводам;
    :Приклеить светодиодную ленту к средней пластине;
    :Припаять кнопки к проводам (x2);
    :Припаять среднюю пластину и провода от кнопок к плате;
end group
group "Финальная сборка"
    :Вставить плату в нижний корпус;
    :Приклеить плату и аккумулятор к нижнему корпусу;
    :Приклеить кнопки к нижнему корпусу (4X7) или к средней пластине (2X2);
    :Вставить среднюю пластину в нижний корпус;
    :В случае 4X7 подготовить верхнюю часть диспенсера, приклеив перегородки ячеек;
    :Вставить верхнюю часть диспенсера в нижний корпус;
end group
:Залить прошивку;
stop
@enduml
