@startuml
start
group "Проверка порта Type-C"
    :Подключить проверочный кабель Type-C;
    :Проверить, что питание (красный) и земля (чёрный) не закорочены (нет прозвона);
    :Проверить, что провод питания (красный) подключен к силовой цепи
    <img:./power-line-checkpoint-PCB-rev1.2.png{scale=0.3}>;
    :Проверить, что провод земли (чёрный) подключен к цепи земли
    <img:./ground-line-checkpoint-PCB-rev1.2.png{scale=0.3}>;
end group
group "Проверка зарядки аккумулятора"
    :Подключить аккумулятор;
    :Подключить зарядный кабель USB-A → Type-C, проверить, что загорается красный светодиод;
    :Проверить наличие 5.1 В на линии питания контроллера
    <img:./controller-power-checkpoint-PCB-rev1.2.png{scale=0.3}>;
    :Отключить зарядный кабель, проверить, что красный светодиод гаснет;
    :Проверить, что на линии питания контроллера по-прежнему есть 5.1 В
    <img:./controller-power-checkpoint-PCB-rev1.2.png{scale=0.3}>;
    :Подключить зарядный кабель Type-C → Type-C к порту, проверить, что загорается красный светодиод;
end group
end
@enduml
